require('plugins.plugins')

require('plugins.nvim-comment')
require('plugins.nvim-treesitter')
require('plugins.nvim-tree')
require('plugins.nvim-autopairs')
require('plugins.nvim-ts-autotag')
require('plugins.bufferline')
require('plugins.lualine')
require('plugins.toggleterm')
require('plugins.alpha')
require('plugins.project')
require('plugins.indent-blankline')
require('plugins.nvim-colorizer')
require('plugins.lspsaga')
require('plugins.todo-comments')
require('plugins.lsp-signature')
