local map = vim.api.nvim_set_keymap

map('n', '<A-k>', ':m .-2<CR>==', {noremap = true})
map('n', '<A-j>', ':m .+1<CR>==', {noremap = true})
map('i', '<A-k>', '<Esc>:m .-2<CR>==gi', {noremap = true})
map('i', '<A-j>', '<Esc>:m .+1<CR>==gi', {noremap = true})
map('v', '<A-k>', ":m '<-2<CR>gv-gv", {noremap = true})
map('v', '<A-j>', ":m '>+1<CR>gv-gv", {noremap = true})
map('', '<C-Down>', '<C-E>', {})
map('', '<C-Up>', '<C-Y>', {})
map('', '<C-n>', ':enew<CR>', {noremap = true, silent = true})
map('', '<C-h>', ':wincmd h<CR>', {noremap = true, silent = true})
map('', '<C-j>', ':wincmd j<CR>', {noremap = true, silent = true})
map('', '<C-k>', ':wincmd k<CR>', {noremap = true, silent = true})
map('', '<C-l>', ':wincmd l<CR>', {noremap = true, silent = true})
map('', '<C-Right>', ':vertical resize +1<CR>', {noremap = true, silent = true})
map('', '<C-Left>', ':vertical resize -1<CR>', {noremap = true, silent = true})
map('n', '<leader>c', ':bdelete<CR>', {})
map('n', '<leader>s', ':w<CR>', {noremap = true, silent = true})
map('n', '<leader>v', ':vsplit<CR>', {noremap = true, silent = true})
map('n', '<leader>h', ':split<CR>', {noremap = true, silent = true})
map('n', '<leader>q', ':q!<CR>', {noremap = true, silent = true})
map('n', '<leader>W', ':wq!<CR>', {noremap = true, silent = true})
map('v', '<TAB>', '>gv', {noremap = true, silent = false})
map('v', '<S-TAB>', '<gv', {noremap = true, silent = false})
map('i', 'jk', '<esc>', {noremap = true, silent = false})
map('n', 'gd', '<cmd>lua vim.lsp.buf.definition()<CR>', {noremap = true, silent = false})

